baseURL: "https://equilaterus.github.io/"
languageCode: "en-us"
theme: "tailbliss"

title: Equilaterus
languageCode: en-us
DefaultContentLanguage: en
enableEmoji: true
enableGitInfo: true
enableRobotsTXT: true
canonifyURLs: true
paginate: 9
darkmode_js:
  - assets/js/darkmode.js
enableInlineShortcodes: true

markup:
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      linkifyProtocol: https
      strikethrough: true
      table: true
      taskList: true
      typographer:
        apostrophe: '&rsquo;'
        disable: false
        ellipsis: '&hellip;'
        emDash: '&mdash;'
        enDash: '&ndash;'
        leftAngleQuote: '&laquo;'
        leftDoubleQuote: '&ldquo;'
        leftSingleQuote: '&lsquo;'
        rightAngleQuote: '&raquo;'
        rightDoubleQuote: '&rdquo;'
        rightSingleQuote: '&rsquo;'
    parser:
      attribute:
        block: false
        title: true
      autoHeadingID: true
      autoHeadingIDType: github
      wrapStandAloneImageWithinParagraph: true
    renderer:
      hardWraps: false
      unsafe: true
      xhtml: false

params:
  ShowFullIntroSlide: true
  ShowSimpleIntroSlide: false
  ShowSponsors: false
  IncludeStars: true
  NavbarSizeClass: max-w-screen-xl # max-w-full
  DisableStayUptodate: false

  GeneralHtmlClass: dark # Set to dark and DisableThemeToggle to run theme in dark mode by default
  DisableThemeToggle: true

  title_description: "Empowering programmers"
  callToAction: Open Source
  heroImage: /game.png
  author: Equilaterus
  authorimage: ../assets/images/global/author.webp
  og_image: /images/tailbliss-cover.png
  moto: "Empowering creators"
  description: "We build technology for videogame creation, maximizing exploration and innovation capabilities for small and medium sized teams."

  details:
    heading: "About us"
    image: "/game-2.png"
    content:
      - text: "We are a team of experienced programmers and creatives that believe in technology as an empowerment mechanism."
      - text: "Our Mission is to empower creative people using software as a foundation, allowing everyone to take on high risk projects without compromising quality or artistic vision."
      - text: "Because of that, we decided to build hand-made technology focused on simplifying development workflows and share almost all of our code with the world."
  moreDetails:
    heading: "Hand-made solutions for game developers"
    image: "/geppetto-ai.png"
    content:
      - text: "We believe that programming is about solving real problems, that is why our code is rocksolid while being fast and easy to understand. Our team has worked on different platforms, engines and toolkits including Unity an Unreal Engine."
      - text: "With that experience, we have started our journey of building a C powered game engine."
      - text: "Stay tunned for upcoming updates."
  sponsors:
    heading: "Backed by world-renowned investors"
    content:
      - text: "Sagittis scelerisque nulla cursus in enim consectetur quam. Dictum urna sed consectetur neque tristique pellentesque. Blandit amet, sed aenean erat arcu morbi. Cursus faucibus nunc nisl netus morbi vel porttitor vitae ut. Amet vitae fames senectus vitae."
    links:
      - text: Meet our investors and advisors
        url: "#"
    logos:
      - identifier: a
        image: "images/global/sample-logo.svg"
        alt: "a"
      - identifier: b
      - identifier: c
      - identifier: d
      - identifier: e
      - identifier: f
  fromTheBlog:
    heading: "From the blog"
    content:
      - text: "News, releases and devlogs."

  stayUpToDate:
    heading: "Stay Up to Date"
    content:
      - text: "Follow us and get access to amazing open-source technology!"
    showForm: false
    showSocial: true
    action: "#"
    label: "Email address"
    placeholder: "Enter your email"
    button: "Notify me"

  social:
    github:
      enabled: true
      url: 'https://github.com/equilaterus'
    facebook:
      enabled: true
      url: 'https://facebook.com/equilaterus'
    instagram:
      enabled: false
      url: 'https://instagram.com/equilaterus'
    linkedin:
      enabled: true
      url: 'https://www.linkedin.com/company/equilaterus'
    twitter:
      enabled: true
      url: '@equilaterusgs'


menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 10
    - identifier: blog
      name: Blog
      url: /
      weight: 20
    - identifier: dropdown
      pre: complexdropdown
      name: Projects
      weight: 40
    - identifier: contact
      name: Contact
      url: /contact/
      weight: 50
    - identifier: legal
      name: Legal
      url: /legal/
      weight: 60
  categories:
    - identifier: prose
      name: Prose
      url: /prose/
      weight: 10
    - identifier: about
      name: About
      url: /about/
      weight: 20
  dropdown:
    - identifier: appearance
      pre: stars # can be stars, comments or piechart
      name: Appearance
      post: "Easy customization"
      url: "#"
      weight: 10
    - identifier: comments
      pre: comments # can be stars, comments or piechart
      name: Comments
      post: "Check your latest comments"
      url: "#"
      weight: 20
    - identifier: analytics
      pre: piechart # can be stars, comments or piechart
      name: Analytics
      post: "Take a look at your statistics"
      url: "#"
      weight: 30
  footer:
    - identifier: home
      name: Home
      url: /
      weight: 10
    - identifier: blog
      name: Blog
      url: /categories/blog/
      weight: 20
    - identifier: contact
      name: Contact
      url: /contact/
      weight: 50
    - identifier: legal
      name: Legal
      url: /legal/
      weight: 60

markup:
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  category: Categories
  tag: Tags

privacy:
  disqus:
    disable: false
  googleAnalytics:
    anonymizeIP: true
    disable: true
    respectDoNotTrack: true
    useSessionStorage: false
  instagram:
    disable: true
    simple: false
  twitter:
    disable: true
    enableDNT: false
    simple: false
  vimeo:
    disable: false
    enableDNT: false
    simple: false
  youtube:
    disable: false
    privacyEnhanced: true

module:
  hugoVersion:
    extended: true
    min: "0.104.0"
